### ISSUE TITLE
Command 'claudia create' Fails with non-npmjs.com Packages

### ISSUE THREAD

**Issue by garystafford** [claudiajs/claudia#142]
* Expected behavior:
When I perform a `claudia create --region us-east-1 --api-module index`, I expect my project to be deployed correctly to AWS, even if it contains npm packages (modules) installed from our private Sonatype Nexus repository or from a public or private GitHub repository, and not from https://www.npmjs.com. The project installed fine when the module was internal to the project. Moving it to an external dependency and requiring it in the main project, claudia fails to deploy.

* What actually happens:
When I perform a `claudia create --region us-east-1 --api-module index` Claudia fails. I get errors, whether I place my module in our private Nexus repo or in a public or private GitHub repo. Note, npm has no problem when I perform a `npm install` from our private Nexus repository or from a GitHub repository. However, Claudia fails when I try to deploy. I have tried the latest v3.0.0 version, as well as previous versions of claudia.js. Remove the package dependency and it deploys fine.

The first error seems it indicate claudia is incorrectly searching npmjs.com instead of Nexus. See lines 16 and 20. Again, `npm install` had no issue, since I was logged into Nexus (`npm login`)

```bash
16 http fetch GET 404 https://registry.npmjs.org/nasa-api-module 585ms
17 silly fetchPackageMetaData error for nasa-api-module@^1.0.1 404 Not Found: nasa-api-module@^1.0.1
18 silly pacote range manifest for claudia-api-builder@^2.5.1 fetched in 5ms
19 silly resolveWithNewModule claudia-api-builder@2.5.1 checking installable status
20 http fetch GET 404 https://registry.npmjs.org/nasa-api-module 328ms
21 silly fetchPackageMetaData error for nasa-api-module@^1.0.1 404 Not Found: nasa-api-module@^1.0.1
22 silly saveTree nasa-api@1.1.0
22 silly saveTree `-- claudia-api-builder@2.5.1
23 verbose stack Error: 404 Not Found: nasa-api-module@^1.0.1
23 verbose stack     at fetch.then.res (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
23 verbose stack     at tryCatcher (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
23 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
23 verbose stack     at Promise._settlePromise (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
23 verbose stack     at Promise._settlePromise0 (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
23 verbose stack     at Promise._settlePromises (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
23 verbose stack     at Async._drainQueue (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
23 verbose stack     at Async._drainQueues (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
23 verbose stack     at Immediate.Async.drainQueues (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
23 verbose stack     at runCallback (timers.js:785:20)
23 verbose stack     at tryOnImmediate (timers.js:747:5)
23 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
24 verbose cwd C:\Users\GARY~1.STA\AppData\Local\Temp\2f09940d-8a98-4d6a-860b-403980ff38c1
25 verbose Windows_NT 10.0.14393
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gary.stafford\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
27 verbose node v8.7.0
28 verbose npm  v5.6.0
  29 error code E404
  30 error 404 Not Found: nasa-api-module@^1.0.1
  31 verbose exit [ 1, true ]
```

Or, error with GitHub

```bash
10 silly lifecycle nasa-api@1.1.0~deploy: Args: [ '/d /s /c',
10 silly lifecycle   'claudia create --region us-east-1 --api-module index' ]
11 silly lifecycle nasa-api@1.1.0~deploy: Returned: code: 1  signal: null
12 info lifecycle nasa-api@1.1.0~deploy: Failed to exec deploy script
13 verbose stack Error: nasa-api@1.1.0 deploy: `claudia create --region us-east-1 --api-module index`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\gary.stafford\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid nasa-api@1.1.0
15 verbose cwd C:\Users\gary.stafford\WebstormProjects\aws-lambda-demo\cookbook\nasa-api
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gary.stafford\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
18 verbose node v8.7.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error nasa-api@1.1.0 deploy: `claudia create --region us-east-1 --api-module index`
22 error Exit status 1
23 error Failed at the nasa-api@1.1.0 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

* Link to a minimal, executable project that demonstrates the problem:
I have created a very simple, sample npm package module, here: https://github.com/garystafford/nasa-api-module.

* Steps to install the project:

Install the module in your own Nexus or Artifactory repository, and require as follows:
```bash
# project.json
"dependencies": {
    "claudia-api-builder": "^3.0.0",
    "nasa-api-module": "^1.0.1"
  }
```

Or, require module from GitHub:
```bash
npm install github:garystafford/nasa-api-module#semver:1.0.1

# project.json
"dependencies": {
    "claudia-api-builder": "^3.0.0",
    "nasa-api-module": "github:garystafford/nasa-api-module#semver:1.0.1"
  }
```

```bash
# index.js
const nasa = require('nasa-api-module')
```
```bash
claudia create --region us-east-1 --api-module index
```

* Steps to reproduce the problem:
Require a custom module in your project, not located on https://www.npmjs.com. Most organizations will have private Nexus or Artifactory repositories, or private GitHub, VSTS, or Bitbucket npm repositories.

**Comment by garystafford** [comment]
I figured out the issue with the Nexus repo. The `.npmrc` config was not retaining the correct path to the Nexus repo. Fixing the `.npmrc` config file corrected the issue, all packages (private and proxied) were pulled through Nexus, and deployment succeeded.

**Comment by stojanovic** [comment]
Thanks for the explanation.
Claudia should handle those situations fine, because we are using `npm pack` command to pack the code and then we do `npm install --production`. `.npmrc` file should be handled correctly with `npm pack`. The only thing that is failing are symlinks because `npm pack` command ignores them.
