### ISSUE TITLE
--use-local-dependencies still fails validation for a local model (via npm link)

### ISSUE THREAD

**Issue by csepulv** [claudiajs/claudia#159]
I have a local module that was added via `npm link`. I use `--use-local-dependencies` when trying to update the lambda module/handler, but in fails in validation:
```
validating package
Error: Cannot find module <my local module>
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/private/var/folders/1t/2sdqf9455kxg1vhrcj84wdcr0000gn/T/3e8f0e36-e087-42f7-bddd-7db592ad1166/src/sns.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
cannot require ./src/<my file> after clean installation. Check your dependencies.
```

But the lambda file and handler load find locally. Any ideas what might be going on?

**Comment by gojko** [comment]
npm link is not yet supported by claudia. use file:// dependencies instead.
