### ISSUE TITLE
--npm-options throws an error

### ISSUE THREAD

**Issue by peebles** [claudiajs/claudia#174]
```sh
claudia pack --npm-options --global-style
TypeError: options.npm-options.split is not a function
    at collectFiles (/Users/peebles/smart-monitor/smart-monitor-cwlogs/node_modules/claudia/src/tasks/collect-files.js:31:77)
    at fsPromise.mkdtempAsync.then.then.then.then (/Users/peebles/smart-monitor/smart-monitor-cwlogs/node_modules/claudia/src/commands/pack.js:48:14)
    at <anonymous>
```

---

* Expected behaviour:

I would expect the options provided be passed to npm.

* What actually happens:

I get an error

* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

**Comment by stokkpiledev** [comment]
> use `claudia pack --npm-options=--global-style` (or if you need multiple args, include in quotes). leaving a space between the argument and value is OK for values without dashes, but if you want to supply a value that starts with a dash, put = between the name and the value, otherwise the command thinks you are providing two arguments

Could you please add this as an example to the docs (including the `=` part) as the format for implementing this cli option is quite different from the others.

I could make a PR if you wish

Thank you

**Comment by sudo-kaizen** [comment]
Could you please add this as an example to the docs (including the = part) as the format for implementing this cli option is quite different from the others.

I could make a PR if you wish

Thank you
