### ISSUE TITLE
nodejs14.x is no longer supported for creating or updating AWS Lambda functions

### ISSUE THREAD

**Issue by KBRR11** [claudiajs/claudia#245]
I have a problem running claudia `create --handler lambda.handler --deploy-proxy-api --region us-east-2`
This is what I get through the console
`creating Lambda lambda.setupRequestListeners
InvalidParameterValueException: The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions.
    at Object.extractError (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kenyramirez/.nvm/versions/node/v20.0.0/lib/node_modules/claudia/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'InvalidParameterValueException',
  time: 2024-03-05T01:26:27.785Z,
  requestId: '45e34c67-5512-4124-9ca1-a774719b0e4d',
  statusCode: 400,
  retryable: false,
  retryDelay: 44.219293973906936
}`

**Comment by KBRR11** [comment]
I resolve it with `--runtime nodejs16.x` can be 18.x or 20.x (current on lambda) 
example: `claudia create --handler lambda.handler --deploy-proxy-api --region us-east-2 --runtime nodejs16.x`
