### ISSUE TITLE
Claudia - update / create - with a npm link package

### ISSUE THREAD

**Issue by ranlandau** [claudiajs/claudia#54]
Hi,

I have a package locally with i've used by npm link, and linked it to my claudia package.
when i do claudia update

i get the following:
`Error: Cannot find module 'intelligodb/dto/search.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)`

But when i browse through the node_modules
i see this:
07/05/2016  01:54 PM    <JUNCTION>     intelligodb [C:\Users\ran\AppData\Roaming\npm\node_modules\intelligodb]

so what the way to use a local package?
Thanks.

**Comment by gojko** [comment]
You can use --use-local-dependencies since 1.4.2 and Claudia will not try to do a clean production install, but just zip up the node_modules as it is locally.

**Comment by ranlandau** [comment]
Still happens.

**Comment by ranlandau** [comment]
`D:\src\searchapi>claudia update --use-local-dependencies
validating package
SyntaxError: Unexpected token var
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at validatePackage (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\src\tasks\validate-package.js:14:15)
    at C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\src\commands\update.js:94:10
    at tryCatcher (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._resolveCallback (C:\Users\ran\AppData\Roaming\npm\node_modules\claudia\node_modules\bluebird\js\release\promise.js:445:14)
cannot require ./app after npm install --production. Check your dependencies.`

**Comment by gojko** [comment]
that's a syntax error in your code most likely. Try launching node from your console and require your main lambda module.

**Comment by ranlandau** [comment]
had 1.4.1 version.
my bad
thanks.
