### ISSUE TITLE
Jasmine tests not using proper AWS profile

### ISSUE THREAD

**Issue by kdybicz** [claudiajs/claudia#98]
Jasmine tests are failing because my AWS user has no rights to play with roles and policies. This doesn't make sense, because I've created proper `claudia-test` profile and I'm using `AWS_PROFILE=claudia-test` to set the profile as the one that should be in use.

* Expected behaviour:

While running tests Jasmine should look for `claudia-test` profile and use those credentials.

* What actually happens:

It looks like it's taking the `default` AWS profile instead, which may work for some people, but will be problematic for people with multiple AWS accounts.

```
▶ npm test

> claudia@2.6.1 pretest /Users/kamil/work/claudia
> eslint .


> claudia@2.6.1 test /Users/kamil/work/claudia
> node spec/support/jasmine-runner.js

Started
error creating generic role { AccessDenied: User: arn:aws:iam::123456789012:user/kamil@xxxxxxxxxxxxx.com is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::123456789012:role/test-generic-role-1486838280580
    at Request.extractError (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kamil/work/claudia/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'User: arn:aws:iam::123456789012:user/kamil@xxxxxxxxxxxxx.com is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::123456789012:role/test-generic-role-1486838280580',
  code: 'AccessDenied',
  time: 2017-02-11T18:38:01.410Z,
  requestId: '37c67ea9-f089-11e6-b87e-071c2588d709',
  statusCode: 403,
  retryable: false,
  retryDelay: 83.65033837197183 }
error cleaning up AccessDenied: User: arn:aws:iam::123456789012:user/kamil@xxxxxxxxxxxxx.com is not authorized to perform: iam:ListRolePolicies on resource: role role-test1486838281418
    at Request.extractError (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kamil/work/claudia/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/kamil/work/claudia/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
FFFFFFFFFF
```

* Steps to reproduce the problem:

Just clone clean repo and run tests, but before ensure that You set as `default` credentials that are invalid or restrictive and put proper one into a profile, which later will be set with use of system env, ie. `AWS_PROFILE=claudia-test`.

**Comment by gojko** [comment]
you should create a .env file and put env variable initialisations there (including aws profile etc), that's how it is supposed to work. The file is ignored by git so stays locally just on your machine. I will update the docs to explain that better

**Comment by kdybicz** [comment]
That's my bad, I was sure that instead of file I can use this approach http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html I guess it's because of convergence of `AWS_PROFILE ` parameter names.

**Comment by gojko** [comment]
I've updated the docs here, should make it easier for the future to find that info: https://github.com/claudiajs/claudia/blob/master/contributing.md#managing-environment-variables-for-testing

**Comment by kdybicz** [comment]
Thanks!
